version: '3.7'

services:
  prometheus:
    image: docker.io/prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - /opt/ITCNE23-SEM-I/monitoring/prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  alertmanager:
    image: docker.io/prom/alertmanager
    container_name: alertmanager
    volumes:
      - /opt/ITCNE23-SEM-I/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    restart: always

  blackbox:
    image: docker.io/prom/blackbox-exporter
    container_name: blackbox
    volumes:
    - /opt/ITCNE23-SEM-I/monitoring/blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml
    ports:
      - "9115:9115"
    restart: always

  grafana:
    image: docker.io/grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always

volumes:
  prometheus-data:
  grafana-storage: