AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS VPC flow log aktivieren '

# Activates AWS VPC flow log to capture information about the IP traffic going to and from network interfaces in the VPC.
Parameters:
  # This Parameter is defined in the Main yaml File like following : VPCModule: !GetAtt VPC.Outputs.StackName
  VPCModule:
    Description: This is the Stack name of the VPC module
    Type: String
  # We will get the TrafficType Parameter from the main yaml file
  TrafficType:
    Type: String
    AllowedValues:
    - ACCEPT
    - REJECT
    - ALL
  # We will get the RetentionDays Parameter from the main yaml file like follow:  RetentionDays: !Ref FlowLogRetentionDays
  RetentionDays:
    Description: 'Specifies the number of days you want to retain log events'
    Type: Number
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150]
  # Parameter to get the VPC ID of the main script
  VPCID:
    Description: This is the Stack name of the VPC module
    Type: String

# creates an IAM role that allows VPC Flow Logs to create log streams and write log events to a CloudWatch Logs log group
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: vpc-flow-logs.amazonaws.com
          Action: sts:AssumeRole
      # crates an IAM policy named "flow-log-policy" and grants permissions to specific AWS CloudWatch Logs actions
      Policies:
      - PolicyName: flow-log-policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            Resource: !GetAtt LogGroup.Arn
  # creates a new CloudWatch Logs Log group with the specified retention period !Ref RetentionDays from the Parameter 
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Ref RetentionDays
  
  # creates a new VPC flow log for the specified VPC resource ID and traffic type (accept, reject, or all), and associates the CloudWatch Logs log group with the VPC flow log.
  FlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt Role.Arn
      LogGroupName: !Ref LogGroup
      ResourceId: !Ref VPCID
      ResourceType: 'VPC'
      TrafficType: !Ref TrafficType

# This code defines the outputs of a CloudFormation stack.
Outputs:
  VPCModule:
    Description: Parameter from the Main Script
    Value: !Ref VPCModule
  TrafficType:
    Description: Parameter from the Main Script
    Value: !Ref TrafficType
  RetentionDays:
    Description: Parameter from the Main Script
    Value: !Ref RetentionDays
  VPCID:
    Description: Parameter from the Main Script
    Value: !Ref VPCID
  
  # The ModuleId output is a custom ID that refers to this specific module within the larger stack.
  ModuleId:
    Value: vpc-flow-log-policy
  # The StackName output returns the name of the CloudFormation stack.
  StackName:
    Value: !Ref AWS::StackName
    # In my Case: VPC-DEV01-FlowLogModule-WDW1Y0R1J44H
  # The Arn output uses the !GetAtt intrinsic function to get the Amazon Resource Name (ARN) of the LogGroup resource created in the stack.
  Arn:
    Value: !GetAtt LogGroup.Arn
    # In My Case: arn:aws:logs:eu-central-2:931336182845:log-group:VPC-DEV01-FlowLogModule-WDW1Y0R1J44H-LogGroup-GFFY5LBTMdmB:*
  # The Name output returns the name of the LogGroup resource created in the stack.
  Name:
    Value: !Ref LogGroup
    # In my Case: VPC-DEV01-FlowLogModule-WDW1Y0R1J44H-LogGroup-GFFY5LBTMdmB
