#cloud-config
package_upgrade: true

ssh_authorized_keys:
  - <your key>

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  - cd /opt
  - sudo git clone https://github.com/blro-ep/ITCNE23-SEM-I.git
  - sudo mkdir -p /etc/apt/keyrings
  - sudo curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
  - sudo apt-get install -y prometheus-node-exporter
  - sudo apt-get install -y containernetworking-plugins
  - sudo apt-get install -y podman
  - podman run -dt --name prometheus -p 9090:9090 docker.io/prom/prometheus
  - podman run -dt --name alertmanager -p 9093:9093 docker.io/prom/alertmanager
  - podman run -dt --name blackbox -p 9115:9115 docker.io/prom/blackbox-exporter
  - podman run -dt --name grafana -p 3000:3000  docker.io/grafana/grafana-enterprise
  