AWSTemplateFormatVersion: 2010-09-09

Description: Deploys a development Amazon Linux instance with a extra 8GB Volume, a user called Bob, the Public SSH Key of my Notebook and a Security Group to log into it. 

# Parameter given to the script
Parameters:
  VPCModule:
    Type: String
    Description: A reference to the VPC Stick Name
  VPCID:
    Type: String
    Description: ID of default VPC
  MyNewKeyPair:
    Type: String
    Description: the Key Pair
  Subnet4ec2:
    Type: String
    Description: the Subnet ID
  DevInstanceProfile:
    Type: String
    Description: the DevInstanceProfile
  InstanceType:
    Type: String
    Description: The Size of the Instance
  # Will get the latest ami from the Parameter Store
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/focal/stable/current/amd64/hvm/ebs-gp2/ami-id'
    #Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  AvailabilityZone:
    Type: String
    Description: The AvailabilityZone the Instance and Volume will be hosted
  SecurityGroup:
    Type: String
    Description: The Security Group you want to add.
  
Resources:

  # Creates an EBS (Elastic Block Store) volume in the specified availability zone given through the Parameter, with a size of 8GB and gp2 volume type
  DevInstanceVolume:
    Type: AWS::EC2::Volume
    Properties:
      VolumeType: gp2
      Size: 8
      AvailabilityZone: !Ref AvailabilityZone
  
  # Configuration for the provision of the ec2 instance
  DevInstance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      # Attache the before configured Security Group to the Instance
      IamInstanceProfile: !Ref DevInstanceProfile
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags: 
        - Key: Name
          Value: basic-instance
        - Key: DeployedWith
          Value: Cloudformation
      KeyName: !Ref MyNewKeyPair
      SubnetId: !Ref Subnet4ec2
      
      # Attaches the before configured Volume to the Instance
      Volumes:
        - Device: /dev/sdh
          VolumeId: !Ref DevInstanceVolume
      IamInstanceProfile: !Ref DevInstanceProfile
      
      UserData:
        Fn::Base64: !Sub |
          #cloud-config
          package_upgrade: true

          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDtN+sKx8MaNh5gpulK9plpe1bxHtYfSlj2WOvMM8cjXzUMRxxIxxPivAohTZYsCW9OwK376GclZd17RqDfx9ifoa1rUpQnyZ1ckB4Xw5zZA+bZintl1L0OAwzTmaITXbly7913BNjkiQ9Vyy3gYwYqEKrmQPfhaWKG3oWCWhQHBE9nllYPtnIspupeEGRaS1rJL1NZH7nRE+5dQMXnIr3pRUDbX0q2WXodYtVuUVaujYCGWDTLzgrLgVWRix165pMfXXJ80wmZCz8JC/vcM7veKiKRtbeTHJSMnxCxN9MpKe/PZqLtS3WywzHkBqF2s208SC0bvfUpxrAKGzUresUWT6+EgeoBDs7IsSwFekAerckSMH0CWXdL0triE52gQK+7mWKPh6vvzONngNiwKQuOD6lnbaVuK2DrJ/Oi4aT2+eonA2ovFCP4BHTgSwc/VVh3++Fu944ZsJOV6zK50uopfCVcrjZ7vs2y15DgwrtARQkaSZVIEwVgZG7FN2n4AEkSvotpElxLNuLbmoKimQdJy96YZYcN2skkOVaaPa1zvB18cT/V5+1ctGJ1rG7jrzkoaATjt4DHEONGfNT5VjE5CYteEExmI9uzEpEuKY+jBWbtRily49ESSEZQd3aCS8svDe8jxvs9zC9N7pzh+5O9PgJsUkyHLJANOJNrWyeOYw== outside@XPS

          packages:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
            - apache2
            - prometheus-node-exporter
            - jq
            - awscli

          runcmd:
            - sudo ufw allow 'Apache'

Outputs:

  WebsiteURL:
    Value: !Sub http://${DevInstance.PrivateIp}
    Description: Application URL

  PrivateIpAddress:
    Description: The public IP address of the deployed instance
    Value: !GetAtt DevInstance.PrivateIp
  
  InstanceID:
    Description: The public IP address of the deployed instance
    Value: !Ref DevInstance

  SSMManager:
    Value: !Sub aws ssm start-session --target ${DevInstance} --profile gmail
    Description: CMD Commend to Connect to the Linux Machine over Session Manager



  SSHConnection:
    Description: The public IP address of the deployed instance
    Value: !Sub ssh ec2-user@${DevInstance.PrivateIp}